jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: master
    - continue-on-error: true
      name: Replace applicationId and name
      run: 'sed -i ''s/applicationId "xyz.zedler.patrick.grocy"/applicationId "xyz.zedler.patrick.grocy.nightly"/''
        app/build.gradle

        sed -i ''s|<string name="app_name" translatable="false">Grocy</string>|<string
        name="app_name" translatable="false">Grocy Nightly</string>|g'' app/src/main/res/values/strings.xml

        '
    - continue-on-error: true
      name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '19'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Rename artifacts
      run: 'mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Grocy-Android-master-$(date
        +''%Y%m%d'').apk

        cp app/src/main/res/raw/changelog.txt app/build/outputs/apk/debug/Grocy-Android-master-$(date
        +''%Y%m%d'')-changelog.txt

        '
    - continue-on-error: true
      name: Upload artifacts
      uses: pyTooling/Actions/releaser@r0
      with:
        files: 'app/build/outputs/apk/debug/*.apk

          app/build/outputs/apk/debug/*.txt

          '
        rm: true
        tag: nightly
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Replace applicationId to default for checkout without git commit
      run: 'sed -i ''s/applicationId "xyz.zedler.patrick.grocy.nightly"/applicationId
        "xyz.zedler.patrick.grocy"/'' app/build.gradle

        sed -i ''s|<string name="app_name" translatable="false">Grocy</string>|<string
        name="app_name" translatable="false">Grocy Nightly</string>|g'' app/src/main/res/values/strings.xml

        '
    - continue-on-error: true
      name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: feature/mlkit_scanner
    - continue-on-error: true
      name: Replace applicationId and name
      run: 'sed -i ''s/applicationId "xyz.zedler.patrick.grocy"/applicationId "xyz.zedler.patrick.grocy.nightly"/''
        app/build.gradle

        sed -i ''s%@string/app_name%Grocy Nightly%'' app/src/main/AndroidManifest.xml

        '
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Rename artifacts
      run: 'mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Grocy-Android-mlkit-$(date
        +''%Y%m%d'').apk

        cp app/src/main/res/raw/changelog.txt app/build/outputs/apk/debug/Grocy-Android-mlkit-$(date
        +''%Y%m%d'')-changelog.txt

        '
    - continue-on-error: true
      name: Upload artifacts
      uses: pyTooling/Actions/releaser@r0
      with:
        files: 'app/build/outputs/apk/debug/*.apk

          app/build/outputs/apk/debug/*.txt

          '
        rm: false
        tag: nightly
        token: ${{ secrets.GITHUB_TOKEN }}
name: Android nightly build
on:
  repository_dispatch:
    types: trigger-ga___android-nightly.yml
